name: Python Build & Test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Set up Python (you can change the version if needed)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3️⃣ Install any dependencies (if you later add requirements.txt)
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4️⃣ Run the Python application with test input and compare output
      - name: Run tests
        run: |
          python3 "Folder Python/main.py" < "Folder Python/tests/input.txt" > "Folder Python/tests/output_github.txt"
          diff -u "Folder Python/tests/expected_for_githubaction.txt" "Folder Python/tests/output_github.txt"
